### ISSUE TITLE
jupiter-service 启动失败

### ISSUE THREAD

**Issue by dearblen** [tiglabs/jupiter#21]
日志是这样的
May  6 06:54:40 localhost kernel: rte_kni: Creating kni...
May  6 06:54:40 localhost jupiter-service[8851]: USER1: dpdk_dev_5tuple_filter_add(): Port0 add 5Tuple filter failed, dst-ip:10.100.6.0, rxq:0.
May  6 06:54:40 localhost jupiter-service[8851]: USER1: dpdk_dev_config_and_set_ipfilter(): dpdk_dev_filter_add failed.
May  6 06:54:40 localhost jupiter-service[8851]: USER1: lb_device_init(): config dpdk dev or add ip filter failed, port_id=0.
May  6 06:54:40 localhost jupiter-service[8851]: USER1: main(): lb_device_init failed.
May  6 06:54:40 localhost NetworkManager[7437]: <info>  [1557096880.1115] manager: (jupiter0): new Ethernet device (/org/freedesktop/NetworkManager/Devices/8)

**Comment by muziding** [comment]
你的网卡是i350吧？
i350网卡有些是支持2tuple，不支持5tuple(可以参考i350的网卡手册或者dpdk的igb驱动代码)。
如果只支持2tuple，是没有办法根据ip对报文分发的，建议你更改jupiter配置文件，只配置两个核。
`[DPDK]
argv = -c 0x3 -n 4`

**Comment by dearblen** [comment]
谢谢 @muziding  按照您的配置 更改后，程序启动成功了
贴下我的配置文件：
[DPDK]
argv = argv = -c 0x3 -n 4

[DEVICE0]
name = jupiter0
ipv4 = 10.100.6.243
netmask = 255.255.255.0
gw = 10.100.6.1
rxqsize = 256
txqsize = 512
mtu = 1500
rxoffload = 0
txoffload = 0
local-ipv4 = 10.100.6.0/24
pci = 0000:02:00.1
